name: build

on:
  push:
    branches:
      - master
jobs:
  build-win64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        curl -L https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20211212-git-0e76372.7z/download > mpv.7z
        7z x mpv.7z
        pip install .[all] pywebview==3.4 pywin32 wheel
        ./gen_pkg.sh --skip-build
        python ./get_pywebview_natives.py
      shell: bash
    - name: PyInstaller Bootloader
      run: |
        ./gen_pkg.sh --get-pyinstaller; cd pyinstaller/bootloader; python ./waf distclean all; cd ..; python setup.py install
        mkdir -p 'c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\typing_extensions-4.1.1-py3.7.egg\EGG-INFO'
        echo > 'c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\typing_extensions-4.1.1-py3.7.egg\EGG-INFO\top_level.txt'
      shell: bash
    - name: Main Build
      run: |
        .\build-win.bat
      shell: cmd
    - name: Artifact Rename
      run: |
        ./artifacts.sh standard
      shell: bash
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: ${{ github.workspace }}/publish/Installer/*.exe
  build-win32:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        curl -L https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-i686-20211212-git-0e76372.7z/download > mpv.7z
        7z x mpv.7z
        pip install .[all] pywebview==3.4 pywin32 wheel
        ./gen_pkg.sh --skip-build
        python ./get_pywebview_natives.py
      shell: bash
    - name: PyInstaller Bootloader
      run: |
        ./gen_pkg.sh --get-pyinstaller; cd pyinstaller/bootloader; python ./waf distclean all; cd ..; python setup.py install
        mkdir -p 'c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\typing_extensions-4.1.1-py3.7.egg\EGG-INFO'
        echo > 'c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\typing_extensions-4.1.1-py3.7.egg\EGG-INFO\top_level.txt'
      shell: bash
    - name: Legacy Build
      run: |
        .\build-win-32.bat
      shell: cmd
    - name: Artifact Rename
      run: |
        ./artifacts.sh legacy
      shell: bash
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-legacy32
        path: ${{ github.workspace }}/publish/InstallerLegacy/*.exe
